"""Render ScanResult to JSON and Markdown."""

from __future__ import annotations

import json
from typing import List

from .config import CHAINS
from .models import ScanResult, Severity

_EMOJI = {
    "Critical": "🔴",
    "High": "🟠",
    "Elevated": "🟡",
    "Low": "🟢",
    "Minimal": "✅",
    "N/A": "⚪",
    "Unknown": "⚪",
}

_SEV_EMOJI = {
    Severity.CRITICAL: "🔴",
    Severity.HIGH: "🟠",
    Severity.MEDIUM: "🟡",
    Severity.LOW: "🔵",
    Severity.INFO: "⚪",
}


def to_json(result: ScanResult, indent: int = 2) -> str:
    return json.dumps(result.to_dict(), indent=indent)


def _explorer_link(result: ScanResult) -> str:
    cfg = CHAINS.get(result.chain)
    if not cfg:
        return result.address
    return f"[{result.address}]({cfg.explorer_url}/address/{result.address})"


def to_markdown(result: ScanResult) -> str:
    band = result.risk_band
    emoji = _EMOJI.get(band, "⚪")
    lines: List[str] = []
    lines.append("# EVM Sentry Risk Report")
    lines.append("")
    lines.append(f"**Address:** {_explorer_link(result)}  ")
    lines.append(f"**Chain:** {result.chain} (chainId {result.metadata.get('chain_id')})  ")
    lines.append(f"**Type:** {'Contract' if result.is_contract else 'EOA / no code'}  ")
    name = result.metadata.get("contract_name")
    if name:
        lines.append(f"**Contract:** {name}  ")
    lines.append("")
    lines.append(f"## {emoji} Risk score: {result.risk_score}/100 — {band}")
    lines.append("")

    counts = result.counts
    summary = " · ".join(
        f"{counts[s.label]} {s.label}"
        for s in sorted(Severity, reverse=True)
        if counts[s.label]
    )
    lines.append(f"**Findings:** {summary or 'none'}")
    lines.append("")

    if result.findings:
        lines.append("## Findings")
        lines.append("")
        ordered = sorted(result.findings, key=lambda f: f.severity, reverse=True)
        for f in ordered:
            se = _SEV_EMOJI.get(f.severity, "")
            lines.append(f"### {se} [{f.severity.label}] {f.title}")
            lines.append(f"`{f.id}` · check: `{f.check}`")
            lines.append("")
            if f.description:
                lines.append(f.description)
                lines.append("")
            if f.evidence:
                ev = ", ".join(f"`{k}`: {v}" for k, v in f.evidence.items())
                lines.append(f"*Evidence:* {ev}")
                lines.append("")
            if f.recommendation:
                lines.append(f"*Recommendation:* {f.recommendation}")
                lines.append("")

    if result.warnings:
        lines.append("## Notes & data limitations")
        lines.append("")
        for w in result.warnings:
            lines.append(f"- {w}")
        lines.append("")

    lines.append("---")
    lines.append(
        "_Generated by [EVM Sentry](https://github.com/ianalloway/evm-sentry). "
        "Heuristic risk signals are not financial advice and not a substitute "
        "for a professional audit._"
    )
    return "\n".join(lines)


def to_terminal(result: ScanResult) -> str:
    """Compact colorless summary for stdout."""
    lines = [
        f"Address : {result.address}",
        f"Chain   : {result.chain}",
        f"Type    : {'contract' if result.is_contract else 'EOA'}",
        f"Score   : {result.risk_score}/100 ({result.risk_band})",
        "Findings:",
    ]
    for f in sorted(result.findings, key=lambda x: x.severity, reverse=True):
        lines.append(f"  [{f.severity.label:8}] {f.id}: {f.title}")
    if not result.findings:
        lines.append("  (none)")
    if result.warnings:
        lines.append("Notes:")
        for w in result.warnings:
            lines.append(f"  - {w}")
    return "\n".join(lines)
